---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${GIT_REPO}    
  triggers:
  - type: commit
  properties:
  - name: CHART_NAME
    value: ${CHART_NAME}
    type: text  
  jobs:
  - name: Build image
    type: builder
    build_type: cr
    artifact_dir: output
    target:
      region_id: ${REGISTRY_REGION_ID}
      api_key: ${API_KEY}
    namespace: ${REGISTRY_NAMESPACE}
    image_name: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # use build script from app source control
      if [ -f ./scripts/build.sh ]; then
        source ./scripts/build.sh
      else
        echo "Did not file build script at ./scripts/build.sh"
        echo "You can copy this file to build a container image: https://github.com/open-toolchain/hello-helm/blob/master/scripts/build.sh"
        exit 1
      fi
- name: VALIDATE
  inputs:
  - type: job
    stage: BUILD
    job: Build image
  triggers:
  - type: stage
  properties:
  - name: FULL_REPOSITORY_NAME
    value: ''
    type: text  
  jobs:
  - name: Vulnerability Advisor
    type: tester
    extension_id: ibm.devops.services.pipeline.crawler.tester
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
    WAIT_TIME: '5'
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build image
  triggers:
  - type: stage
  properties:
  - name: buildprops
    value: build.properties
    type: file
  - name: CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: CHART_NAME
    value: ${CHART_NAME}
    type: text      
  - name: IMAGE_PULL_SECRET_NAME
    value: ${IMAGE_PULL_SECRET_NAME}
    type: text      
  jobs:
  - name: Deploy Helm Chart
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      # use deploy script from app source control
      if [ -f ./scripts/deploy.sh ]; then
        source ./scripts/deploy.sh
      else
        echo "Did not file deploy script at ./scripts/deploy.sh"
        echo "You can copy this file to deploy a container image to Kubernetes: https://github.com/open-toolchain/hello-helm/blob/master/scripts/deploy.sh"
        exit 1
      fi
